POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Third blog",
  "author": "Queen Elizabeth",
  "url": "www.fakeurl.com",
  "likes": 0,
  "userid": "5fdf6733b6c4332351d0efa2"
}