POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Third blog",
  "author": "Queen Elizabeth",
  "url": "www.fakeurl.com",
  "likes": 0,
  "userID": "5cfd61844e8b621fe5c36fc6"
}